"""Make-BytePatches.py - build the installer's byte-patch table (developer tool).

Compares the OEM files from the extracted disc with the patched copies in a working
install and writes Patches\\nascar-bytepatches.txt, which Install-NASCAR-GVR-Portable.ps1
applies with no Python needed. Only same-size patches are allowed: every patch here
replaces bytes in place, and the installer verifies the OEM bytes before writing.

Format:
    file <path relative to the install root>
    <hex offset> <OEM bytes hex> <patched bytes hex>
    ...

Usage: python Make-BytePatches.py <payload File_Group> <working install> <out file>
"""
import os
import sys

# install-relative path -> path inside the disc payload (File_Group)
FILES = [
    r"Shell\bin\Dongle.dll",
    r"Shell\bin\PlugIns\HerculesPlugIn.dll",
    r"Shell\bin\PlugIns\NASCARPlugIn.dll",
    r"Shell\Shell.am",
    r"Shell\NASCAR_Attract.am",
    r"Shell\NASCAR_Selection.am",
]
AM_MENUS = ["Adjust_Gamma", "Adjust_Resolution", "Adjust_Vibrance", "Control_Test",
            "Histogram_Continue", "Histogram_GameTime", "Monitor_Test", "Motion_Test",
            "Operator New", "Operator", "SetLinkID", "SetLinkIDAttract", "Speaker_Test",
            "VersionMismatch"]
FILES += [r"Shell\OPERATOR_MENUS\%s.am" % n for n in AM_MENUS]

MERGE_GAP = 8   # runs closer than this are written as one patch


def find(root, rel):
    """case-insensitive path lookup (the disc and the install differ in case)"""
    cur = root
    for part in rel.split("\\"):
        hit = [e for e in os.listdir(cur) if e.lower() == part.lower()]
        if not hit:
            raise FileNotFoundError(os.path.join(cur, part))
        cur = os.path.join(cur, hit[0])
    return cur


def runs(a, b):
    out, i, n = [], 0, len(a)
    while i < n:
        if a[i] != b[i]:
            s = i
            while i < n and a[i] != b[i]:
                i += 1
            if out and s - out[-1][1] <= MERGE_GAP:
                out[-1][1] = i
            else:
                out.append([s, i])
        else:
            i += 1
    return out


def main():
    payload, install, out = sys.argv[1:4]
    lines = ["# NASCAR GVR byte patches - generated by Tools\\Make-BytePatches.py, do not edit.",
             "# file <install-relative path> / <hex offset> <OEM hex> <patched hex>"]
    for rel in FILES:
        oem = open(find(os.path.join(payload, "NASCAR"), rel), "rb").read()
        new = open(find(install, rel), "rb").read()
        if len(oem) != len(new):
            sys.exit("size differs, not a byte patch: " + rel)
        r = runs(oem, new)
        lines.append("file " + rel)
        for s, e in r:
            lines.append("%x %s %s" % (s, oem[s:e].hex(), new[s:e].hex()))
        print("%-45s %3d patch(es), %5d bytes" % (rel, len(r), sum(e - s for s, e in r)))
    with open(out, "w", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
